export type ReviewJobType = "Garage" | "Basement" | "Commercial";

export type ReviewItem = {
  id: string;
  name: string;
  date: string;
  town: string;
  job: ReviewJobType;
  text: string;
};

export const ALL_REVIEWS: ReviewItem[] = [
  {
    id: "1",
    name: "Michael R.",
    date: "Mar 12, 2025",
    town: "Commack",
    job: "Garage",
    text: "Edges are crisp and the flake is consistent across the whole slab. Owner stayed through final topcoat — rare nowadays.",
  },
  {
    id: "2",
    name: "Samantha P.",
    date: "Feb 2, 2025",
    town: "Bay Shore",
    job: "Garage",
    text: "Oil stains are gone and cleanup is stupid-easy. Crew protected everything and didn’t rush the prep.",
  },
  {
    id: "3",
    name: "James L.",
    date: "Jan 18, 2025",
    town: "Hauppauge",
    job: "Commercial",
    text: "Shop schedule was tight — they communicated clearly and delivered a uniform gloss across the bay.",
  },
  {
    id: "4",
    name: "Elena V.",
    date: "Dec 9, 2024",
    town: "Syosset",
    job: "Garage",
    text: "Metallic looks incredible in person. Photos don’t do the depth justice.",
  },
  {
    id: "5",
    name: "Daniel K.",
    date: "Nov 27, 2024",
    town: "Plainview",
    job: "Basement",
    text: "Grind and seal gave us the modern concrete vibe without turning the basement into an ice rink.",
  },
  {
    id: "6",
    name: "Nicole H.",
    date: "Nov 4, 2024",
    town: "Garden City",
    job: "Garage",
    text: "Straight answers about moisture and realistic timelines. Floor feels solid.",
  },
  {
    id: "7",
    name: "Chris A.",
    date: "Oct 19, 2024",
    town: "Ronkonkoma",
    job: "Garage",
    text: "Two-car garage + storage area — transitions look intentional, not patched together.",
  },
  {
    id: "8",
    name: "Priya S.",
    date: "Oct 1, 2024",
    town: "Hauppauge",
    job: "Commercial",
    text: "We asked for durability first — they didn’t upsell theatrics we didn’t need.",
  },
  {
    id: "9",
    name: "Tom W.",
    date: "Sep 14, 2024",
    town: "Kings Point",
    job: "Garage",
    text: "High expectations neighborhood — the finish holds up to scrutiny.",
  },
  {
    id: "10",
    name: "Ashley D.",
    date: "Aug 30, 2024",
    town: "Deer Park",
    job: "Garage",
    text: "Kids bikes, salt in winter, hot tires — still cleans up fast.",
  },
  {
    id: "11",
    name: "Brian C.",
    date: "Aug 8, 2024",
    town: "Dix Hills",
    job: "Garage",
    text: "Epoxy over rough concrete looked impossible — they fixed low spots honestly.",
  },
  {
    id: "12",
    name: "Rachel M.",
    date: "Jul 22, 2024",
    town: "East Northport",
    job: "Basement",
    text: "Nice crew. Quiet equipment considerations for neighbors — appreciated.",
  },
  {
    id: "13",
    name: "Victor P.",
    date: "Jul 6, 2024",
    town: "Central Islip",
    job: "Commercial",
    text: "Warehouse lane markings look sharp. Holds up to forklift traffic.",
  },
  {
    id: "14",
    name: "Lauren G.",
    date: "Jun 18, 2024",
    town: "Roslyn Heights",
    job: "Garage",
    text: "Scheduling was painless. Finish matches our exterior upgrades.",
  },
  {
    id: "15",
    name: "Kevin S.",
    date: "Jun 2, 2024",
    town: "Melville area",
    job: "Garage",
    text: "They didn’t disappear after deposit — communication stayed strong.",
  },
  {
    id: "16",
    name: "Angela F.",
    date: "May 12, 2024",
    town: "Lynbrook",
    job: "Basement",
    text: "Moisture concerns were handled responsibly — no false promises.",
  },
  {
    id: "17",
    name: "Marcus J.",
    date: "Apr 28, 2024",
    town: "West Babylon area",
    job: "Garage",
    text: "Looks like a showroom now. Friends already asked for your number.",
  },
  {
    id: "18",
    name: "Olivia T.",
    date: "Apr 9, 2024",
    town: "Cold Spring Harbor",
    job: "Garage",
    text: "Detailed masking and cleanup — you can tell they’ve done this a thousand times.",
  },
  {
    id: "19",
    name: "Jason H.",
    date: "Mar 21, 2024",
    town: "Smithtown area",
    job: "Garage",
    text: "Hot tire pickup was my fear — still looks brand new months later.",
  },
  {
    id: "20",
    name: "Stephanie E.",
    date: "Mar 3, 2024",
    town: "Mineola",
    job: "Commercial",
    text: "Professional installation for our shop entrance — customers comment on it.",
  },
  {
    id: "21",
    name: "Greg N.",
    date: "Feb 16, 2024",
    town: "Fort Salonga",
    job: "Garage",
    text: "Three-car garage completed quickly — owner operated grinder like a surgeon.",
  },
  {
    id: "22",
    name: "Monica L.",
    date: "Jan 29, 2024",
    town: "East Hills",
    job: "Garage",
    text: "Even lighting across the flake — no blotchy patches.",
  },
  {
    id: "24",
    name: "Yasmin Q.",
    date: "Dec 14, 2023",
    town: "Stony Brook",
    job: "Basement",
    text: "Honest guidance between epoxy vs polyaspartic — chose what fit our timeline.",
  },
];
